### ISSUE TITLE
steaming site to list movies that are registered in backend

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#95] opened 2020-06-10 08:13 UTC
- if there is no price for a movie, use default price per region

**Comment by troggy** [comment] 2020-06-11 06:56
fetching price from database is covered by #88 and is not related to streamer anyway. Apart from price looks like duplicate for #96

**Comment by troggy** [comment] 2020-06-13 15:09
duplicate of #96

**Closed by troggy** 2020-06-13 15:09 UTC
Labels: question
